[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  for = "/js/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/javascript"

[[headers]]
  for = "/style/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "text/css"
